apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: be-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rejeesh-gpkrn/dotnet_core_backend.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: trial

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
