apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rejeeshgpkrn/demo-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
